### ISSUE TITLE
Make networking more robust

### ISSUE THREAD

**Issue by dylwhich** [umbc-hackafe/bridgesim#6]
Currently a client-id can only be reused a few times before its connections failed and I don't know why. We should fix this and figure out a solution for synchronizing multiple tabs from the same browser. Or, just not do that.

**Comment by SashaCrofter** [comment]
Here is a log dump of what I believe is this issue.

```
[10/Jan/2015:03:15:14] ENGINE Serving on http://0.0.0.0:9000
[10/Jan/2015:03:15:14] ENGINE Bus STARTED
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /weapons HTTP/1.1" 200 1414 "" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/three/three.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/three/Group.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/three/MTLLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/three/OBJLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/map.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/three/DDSLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /css/common/fullwindow_canvas.css HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/client.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/three/OBJMTLLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/three/CompressedTextureLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/screenclient.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /js/weapons.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /css/index.css HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
Client connected!
Connected new client 94bbe962-720f-42dc-aef4-2f9bcc868eb2
127.0.0.1 - - [10/Jan/2015:03:15:16] "GET /client HTTP/1.1" 101 - "" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
>>> b'{"seq":218023129051461,"op":"functions","args":[],"kwargs":{},"context":null,"expand":false}'
>>> b'{"seq":218023129051462,"op":"specials","args":[],"kwargs":{},"context":null,"expand":false}'
>>> b'{"seq":218023129051463,"op":"whoami","args":[],"kwargs":{},"context":null,"expand":false}'
>>> b'{"seq":218023129051464,"op":"ClientUpdater__requestUpdates","args":["entity",10],"kwargs":{},"context":null,"expand":false}'
>>> b'{"seq":218023129051465,"op":"whoami","args":[],"kwargs":{},"context":null,"expand":false}'
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /weapons HTTP/1.1" 200 1414 "" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
Traceback (most recent call last):
  File "./main.py", line 119, in <module>
    universe.tock()
  File "/home/sasha/dev/python/bridgesim/src/server/Universe.py", line 79, in tock
    i.tick()
  File "/home/sasha/dev/python/bridgesim/src/server/Client.py", line 200, in tick
    self.sendUpdates(toUpdate)
  File "/home/sasha/dev/python/bridgesim/src/server/Client.py", line 165, in sendUpdates
    self.client.queueUpdate(kind, self.client.api.expand(entity))
  File "/home/sasha/dev/python/bridgesim/src/server/Client.py", line 106, in queueUpdate
    raise ClientClosedException()
Client.ClientClosedException
/usr/lib/python3.4/site-packages/cherrypy/process/wspbus.py:233: RuntimeWarning: The main thread is exiting, but the Bus is in the states.STARTED state; shutting it down automatically now. You must either call bus.block() after start(), or call bus.exit() before the main thread exits.
  "main thread exits." % self.state, RuntimeWarning)
[10/Jan/2015:03:15:19] ENGINE Bus STOPPING
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/three/OBJMTLLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/three/three.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/three/Group.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/three/MTLLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/three/OBJLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/three/CompressedTextureLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/three/DDSLoader.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /css/common/fullwindow_canvas.css HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/map.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/screenclient.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/client.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /js/weapons.js HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
127.0.0.1 - - [10/Jan/2015:03:15:19] "GET /css/index.css HTTP/1.1" 304 - "http://localhost:9000/weapons" "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
[10/Jan/2015:03:15:24] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9000)) shut down
[10/Jan/2015:03:15:24] ENGINE Stopped thread 'Autoreloader'.
[10/Jan/2015:03:15:24] ENGINE Stopped thread '_TimeoutMonitor'.
[10/Jan/2015:03:15:24] ENGINE Terminating WebSocket processing
[10/Jan/2015:03:15:24] ENGINE Bus STOPPED
[10/Jan/2015:03:15:24] ENGINE Bus EXITING
[10/Jan/2015:03:15:24] ENGINE Bus EXITED
```

**Comment by dylwhich** [comment]
Completed in dc35d35b
